name: ⚒️ DayPass Build

on:
    push:
        branches:
        - main
        - dev

    workflow_dispatch:


permissions:
    contents: read


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: 🔎 Checkout Repository
        uses: actions/checkout@v4


      - name: 🗓️ Restore DayPass Cache
        uses: actions/cache@v4
        with:
          path: |
            cache
          key: daypass-${{ runner.os }}-${{ hashFiles('config/architectures.json') }}
          restore-keys: |
            daypass-${{ runner.os }}-[cite: 3]


      - name: 🛡️ Run ShellCheck on Scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './core'
          severity: warning
          # exclude: "SC1091" 


      - name: 🛠 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bash \
            curl \
            jq \
            coreutils \
            findutils \
            zip[cite: 1]


      - name: 📝 Make Scripts Executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;[cite: 1]


      - name: 👷 Build DayPass
        shell: bash
        run: |
          ./core/orchestrator.sh[cite: 1]


      - name: 🧪 Validate Build
        shell: bash
        run: |
          test -f output/install.sh
          test -f output/manifest.json[cite: 1]


      - name: 🔍 Debug Output
        shell: bash
        run: |
            tree -L 3 output[cite: 1]