name: 🧠 DayPass Manifests

on:
  push:
    branches:
      - main
      - dev 
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate DayPass Manifests
        run: |
          chmod +x ./metadata/manifest.sh
          
          export DAYPASS_OUTPUT_DIR="./output"
          export DAYPASS_ARCH_FILE="./metadata/arch.json" 
          export DAYPASS_CORE_DIR="."
          
          mkdir -p "$DAYPASS_OUTPUT_DIR"
          
          ./metadata/manifest.sh
          
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4