name: 🗿 DayPass Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Restore Cache
      - name: 🗓️ Restore DayPass Cache
        uses: actions/cache@v4
        with:
          path: |
            cache
          key: daypass-${{ runner.os }}-${{ hashFiles('config/architectures.json') }}
          restore-keys: |
            daypass-${{ runner.os }}-

      # GitHub Pages
      - name: 😼 Setup Pages
        uses: actions/configure-pages@v5

      # Install Tools
      - name: 🛠️ Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bash \
            curl \
            jq \
            coreutils \
            findutils \
            zip

      # chmod
      - name: 📝 Make Scripts Executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;

      # Build
      - name: 👷‍♀️ Build DayPass
        shell: bash
        run: |
          ./core/orchestrator.sh

      # Validate
      - name: 🧪 Validate Build
        shell: bash
        run: |
          test -f output/install.sh
          test -f output/manifest.json

      # Upload Pages
      - name: 📤 Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: 🔍 Debug Output Structure
        shell: bash
        run: |
          tree -L 3 output

      # Package Release ZIP
      - name: 📦 Create DayPass Release Package
        shell: bash
        run: |
          VERSION=$(date +%Y.%m.%d)
          ARCH=$(jq -r '.architectures[0].name' output/manifest.json)
          ZIP_NAME="DayPass_${ARCH}_v${VERSION}.zip"
          echo "[INFO] Creating $ZIP_NAME"
          cd output

          zip -r "../$ZIP_NAME" \
            passwall_luci \
            passwall2 \
            passwall_packages \
            -x "*.sh" \
            -x "manifest.json" \
            -x "index.json"

          cd ..

          sha256sum "$ZIP_NAME" > "${ZIP_NAME}.sha256"
          echo "[ OK ] Release package created"
          ls -lh "$ZIP_NAME"

      - name: 🚀 Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: DayPass v${{ github.run_number }}
          files: |
            DayPass_*.zip
            DayPass_*.sha256

  deploy:

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Deploy Pages
      - name: 🚀 Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        